# additional data require to create the Docker image
packaging:
  # files to add to the build, usually used with ADD in the Dockerfile
  add:
    # the plugin always filters
    - target/${project.build.finalName}.jar
    - hello-world.yml
# optional list of port to expose on the host
ports:
  - 8080
  - 8081
# containers that this should be linked to, started before this one and stopped afterwards
links:
  - mysql:db
healthChecks:
  pings:
    # I use localhost here as I'm using Boot2 Docker. If you use Linux is a multi-host set-up, then you can use
    # __CONTAINER.IP__
    - url: http://localhost:8080/hello-world
      timeout: 60000
  logPatterns:
    - "Successfully released change log lock"
    - pattern: "Started SocketConnector"
      timeout: 60000
tag: registry/${project.artifactId}-app:${project.version}
